version: "3.5"

services:
  server:
    build:
      context: ./docker
      dockerfile: Dockerfile
    container_name: Golang_service
    working_dir: /server
    volumes:
      - .:/server
    ports:
      - "5000:5000"
    depends_on:
      - postgresqldb
    entrypoint: go run main.go
    restart: always

  postgresqldb:
    build:
      context: ./psql
      dockerfile: sqlinit.Dockerfile
    container_name: DB_service
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=ui_test
      - POSTGRES_PASSWORD=66556622
      - PGDATA=/var/lib/postgresql/data/pgdata
    restart: always


