version: "3.5"

services:
  server:
    build:
      # context: .
      dockerfile: Dockerfile
    working_dir: /server
    volumes:
      - .:/server
    ports:
      - "5000:5000"
    depends_on:
      - db
    entrypoint: go run main.go
    restart: always

  postgresqldb:
    build:
      dockerfile: ./psql/sqlinit.Dockerfile
    container_name: postgresqldb
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=ui_test
      - POSTGRES_PASSWORD=66556622
      - PGDATA=/var/lib/postgresql/data/pgdata
    restart: always

  pgadmin:
    container_name: pgadmin
    image: thajeztah/pgadmin4
    ports:
      - "5050:5050"
    restart: always

